spring:
  application:
    name: raspberry
  datasource:
    url: jdbc:postgresql://localhost:5432/cmddev?currentSchema=cmddata
    username: cmddev
    password: cmddev

  flyway:
    enabled: true
    table: ms_changelog
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

schedule:
  # cron:  second(0-59) minute(0-59) hour(0-23) day-of-month(1-28/31) month-of-year(1-12) day-of-week(1-7)
  runspeedtest:
    cron: 0 */10 * * * ?
  runping:
    cron: 0 * * * * ?

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/cmdpro?currentSchema=cmddata
    username: cmdpro
    password: cmdpro!1234

schedule:
  # cron:  second(0-59) minute(0-59) hour(0-23) day-of-month(1-28/31) month-of-year(1-12) day-of-week(1-7)
  runspeedtest:
    cron: 0 */10 * * * ?
  runping:
    cron: 0 * * * * ?

---
spring:
  config.activate.on-profile: prodview
  datasource:
    url: jdbc:postgresql://192.168.2.19:5432/cmdpro?currentSchema=cmddata
    username: cmdpro
    password: cmdpro!1234

schedule:
  # cron:  second(0-59) minute(0-59) hour(0-23) day-of-month(1-28/31) month-of-year(1-12) day-of-week(1-7)
  runspeedtest:
    cron: 0 0 12 31 12 ?
  runping:
    cron: 0 0 12 31 12 ?

